resources:
  - name: signer
    type: docker-image
    source:
      repository: quay.io/quay/apostille-signer
      username: {{quay-robot-username}}
      password: {{quay-robot-password}}
      check: true
  - name: server
    type: docker-image
    source:
      repository: quay.io/quay/apostille
      username: {{quay-robot-username}}
      password: {{quay-robot-password}}
      check: true
  - name: apostille-build-util
    type: docker-image
    source:
      repository: quay.io/quay/apostille-build-util
      username: {{quay-robot-username}}
      password: {{quay-robot-password}}
  - name: apostille-pull-request
    type: git
    source:
      uri: git@github.com:coreos-inc/apostille.git
      branch: master
      private_key: {{quay-git-private-key}}
      disable_ci_skip: true
  - name: quay-policies
    type: git
    source:
      uri: git@github.com:coreos-inc/quay-policies.git
      branch: master
      private_key: {{quay-policies-git-private-key}}
      disable_ci_skip: true

jobs:
  - name: deploy-to-staging
    max_in_flight: 1
    plan:
      - aggregate:
        - get: signer
          trigger: true
        - get: server
          trigger: true
      - get: apostille-pull-request
      - get: apostille-build-util
      - get: quay-policies
      - task: deploy_to_staging
        image: apostille-build-util
        file: apostille-pull-request/ci/tasks/deploy_to_staging.yaml
        params: {KUBE_CTL_CONFIG: {{kubectl-config}} }