unit-test:
  stage: test
  image: golang:1.8
  before_script:
    - mkdir -p /go/src/github.com/coreos-inc/apostille
    - cp -a /quay/coreos-inc__apostille/* /go/src/github.com/coreos-inc/apostille
    - cd /go/src/github.com/coreos-inc/apostille
  script:
    - make test
  allow_failure: false

mysql-test:
  stage: test
  image: docker:dind
  before_script:
    - apk update
    - apk add bash py-pip
    - pip install docker-compose
    - mkdir -p /go/src/github.com/coreos-inc/apostille
    - cp -a /quay/coreos-inc__apostille/* /go/src/github.com/coreos-inc/apostille
    - cd /go/src/github.com/coreos-inc/apostille
    - chmod 0777 ./aposql/mysql-initdb.d/*
  script:
    - integration/integration.sh mysql
  tags:
    - kubernetes
  variables:
    DOCKER_HOST: tcp://docker-host.gitlab-runner.svc.cluster.local:2375
  allow_failure: false

postgres-test:
  stage: test
  image: docker:latest
  before_script:
    - apk update
    - apk add bash py-pip
    - pip install docker-compose
    - mkdir -p /go/src/github.com/coreos-inc/apostille
    - cp -a /quay/coreos-inc__apostille/* /go/src/github.com/coreos-inc/apostille
    - cd /go/src/github.com/coreos-inc/apostille
  script:
    - cd /quay/coreos-inc__apostille
    - integration/integration.sh postgresql
  services:
    - docker:dind
  tags:
    - kubernetes
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://docker-host.gitlab-runner.svc.cluster.local:2375
  allow_failure: false


#container-build:
#  only:
#  - master
#  before_script:
#  - docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
#  image: docker:git
#  script:
#   - docker build -t quay.io/quay/apostille:${CI_COMMIT_REF_SLUG} -f server.Dockerfile .
#   - docker build -t quay.io/quay/apostille-signer:${CI_COMMIT_REF_SLUG} -f signer.Dockerfile .
#   - docker push quay.io/quay/apostille:${CI_COMMIT_REF_SLUG}
#   - docker push quay.io/quay/apostille-signer:${CI_COMMIT_REF_SLUG}
#  stage: docker_build
#  tags:
#  - kubernetes
#  variables:
#    DOCKER_DRIVER: overlay
#    DOCKER_HOST: tcp://docker-host.gitlab-runner.svc.cluster.local:2375

stages:
 - test
 - docker_build

variables:
  FAILFASTCI_NAMESPACE: quay
