---
platform: linux
inputs:
  - name: apostille-pull-request
  - name: quay-policies-encrypted
  - name: signer
  - name: server
run:
  path: /bin/bash
  args:
    - -c
    - |
      echo $KUBE_CTL_CONFIG | tr -d '\n' | base64 --decode > /kube_config && export KUBECONFIG=/kube_config
      echo $QUAY_POLICIES_DECRYPT_KEY | tr -d '\n' | base64 --decode >  /concourse-quay-policies.key

      gpg --import /concourse-quay-policies.key
      cd quay-policies-encrypted
      git-crypt unlock
      cd ..

      export SIGNER_GIT_SHA=`cat signer/docker_inspect.json | jq --raw-output '.[0].ContainerConfig.Labels.GIT_SHA'`
      export SIGNER_BUILD_UUID=`cat signer/docker_inspect.json | jq --raw-output '.[0].ContainerConfig.Labels.BUILD_UUID'`

      export SERVER_GIT_SHA=`cat server/docker_inspect.json | jq --raw-output '.[0].ContainerConfig.Labels.GIT_SHA'`
      export SERVER_BUILD_UUID=`cat server/docker_inspect.json | jq --raw-output '.[0].ContainerConfig.Labels.BUILD_UUID'`

      if [ "$SIGNER_GIT_SHA" == "$SERVER_GIT_SHA" ] && [ "$SIGNER_BUILD_UUID" == "$SIGNER_BUILD_UUID" ] ; then
        helm init --client-only
        cd apostille-pull-request/helm/apostille-app

        git checkout $SIGNER_GIT_SHA

        export SEMVER=`git tag | sort -r | head -1 | sed 's/v//g'`-staging+${SIGNER_BUILD_UUID}
        echo "version: ${SEMVER}" >> Chart.yaml

        helm registry login -u $QUAY_APP_USERNAME -p $QUAY_APP_PASSWORD quay.io
        helm registry push --namespace quay quay.io
        helm upgrade  -f ../../../quay-policies-encrypted/tools/cloudconfig/secrets/helm-values/apostille-staging.yaml \
                      --set apostille_image=quay.io/quay/apostille:${SERVER_GIT_SHA},signer_image=quay.io/quay/apostille-signer:${SIGNER_GIT_SHA} \
                      --install \
                      apostille-staging .

        exit 0
      else
        if [ "$SIGNER_GIT_SHA" != "$SERVER_GIT_SHA" ]; then
          echo "SIGNER_GIT_SHA ($SIGNER_GIT_SHA) not equal to SERVER_GIT_SHA ($SERVER_GIT_SHA)"
        fi

        if [ "$SIGNER_BUILD_UUID" != "$SERVER_BUILD_UUID" ]; then
          echo "SIGNER_BUILD_UUID ($SIGNER_BUILD_UUID) not equal to SERVER_BUILD_UUID ($SERVER_BUILD_UUID)"
        fi

        exit 1
      fi
