---
platform: linux
inputs:
  - name: gh-release
  - name: quay-policies-encrypted
  - name: apostille-code
run:
  path: /bin/bash
  args:
    - -c
    - |
      echo $KUBE_CTL_CONFIG | tr -d '\n' | base64 --decode > /kube_config && export KUBECONFIG=/kube_config
      echo $QUAY_POLICIES_DECRYPT_KEY > /concourse-quay-policies.key

      gpg import /concourse-quay-policies.key
      cd quay-polices-encrypted
      git-crypt unlock
      cd ..

      helm init --client-only
      export SEMVER=`cat gh-release/version | sed 's/v//g'`
      export TAG=`cat gh-release/tag`

      cd apostille-code/helm/apostille-app

      export GIT_SHA=`git rev-list --abbrev-commit -n 1 $TAG`

      git checkout $GIT_SHA

      echo "version: ${SEMVER}" >> Chart.yaml

      helm registry login -u $QUAY_APP_USERNAME -p $QUAY_APP_PASSWORD quay.io
      helm registry push --namespace quay quay.io

      helm upgrade  -f ../../../quay-policies-encrypted/tools/cloudconfig/secrets/helm-values/apostille-prod.yaml \
                    --set apostille_image=quay.io/quay/apostille:${GIT_SHA},signer_image=quay.io/quay/apostille-signer:${GIT_SHA} \
                    --install \
                    apostille .