---
platform: linux
inputs:
  - name: apostille-pull-request
run:
  path: /bin/sh
  args:
    - -c
    - |
      export AWS_DEFAULT_REGION=us-east-1
      export APOSTILLE_FILE_NAME=apostille.tar.gz
      export APOSTILLE_FOLDER_NAME=apostille-pull-request

      cd ${APOSTILLE_FOLDER_NAME}
      export GIT_SHA=$(git rev-parse --short --verify HEAD)
      echo "LABEL GIT_SHA=${GIT_SHA}" >> server.Dockerfile
      echo "LABEL GIT_SHA=${GIT_SHA}" >> signer.Dockerfile
      cd ..

      tar -cv apostille-pull-request | gzip > ${APOSTILLE_FILE_NAME}

      aws s3 cp ./apostille.tar.gz s3://test-apstille-gzip/${GIT_SHA}/${APOSTILLE_FILE_NAME}

      export ARCHIVE_URL=`aws s3 presign s3://test-apstille-gzip/${GIT_SHA}/${APOSTILLE_FILE_NAME}`


      echo "{\"archive_url\":\"${ARCHIVE_URL}\",\"docker_tags\":[\"${GIT_SHA}\"],\"context\":\"/${APOSTILLE_FOLDER_NAME}\",\"dockerfile_path\":\"/${APOSTILLE_FOLDER_NAME}/server.Dockerfile\"}" > post.json
      curl -X POST -d @post.json https://quay.io/api/v1/repository/quay/apostille/build/ --header "Content-Type:application/json" --header "Authorization:Bearer ${QUAY_TOKEN}"

      echo "{\"archive_url\":\"${ARCHIVE_URL}\",\"docker_tags\":[\"${GIT_SHA}\"],\"context\":\"/${APOSTILLE_FOLDER_NAME}\",\"dockerfile_path\":\"/${APOSTILLE_FOLDER_NAME}/signer.Dockerfile\"}" > post.json
      curl -X POST -d @post.json https://quay.io/api/v1/repository/quay/apostille-signer/build/ --header "Content-Type:application/json" --header "Authorization:Bearer ${QUAY_TOKEN}"
