kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{.Values.service}}
  namespace: {{.Values.apostille_namespace}}
  labels:
    app: apostille
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apostille
  template:
    metadata:
      namespace: apostille
      labels:
        app: apostille
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
              "name": "migrate-apostille",
              "image": "{{.Values.apostille_image}}",
              "imagePullPolicy": "IfNotPresent",
              "command": ["/bin/sh", "-c", "/go/src/github.com/coreos-inc/apostille/migrations/migrate.sh"],
              "env": [
                {
                  "name": "DB_URL",
                  "valueFrom": {
                    "configMapKeyRef": {
                      "name": "apostille-config",
                      "key": "db.url"
                    }
                  }
                },
                {
                  "name": "ROOT_DB_URL",
                  "valueFrom": {
                    "configMapKeyRef": {
                      "name": "apostille-config",
                      "key": "root.db.url"
                    }
                  }
                },
                {
                  "name": "MIGRATIONS_PATH",
                  "valueFrom": {
                    "configMapKeyRef": {
                      "name": "apostille-config",
                      "key": "migrations.path"
                    }
                  }
                }
              ]
            },
            {
              "name": "migrate-apostille-signer",
              "image": "{{.Values.signer_image}}",
              "imagePullPolicy": "IfNotPresent",
              "command": ["/bin/sh", "-c", "/go/src/github.com/docker/notary/migrations/migrate.sh" ],
              "env": [
                {
                  "name": "DB_URL",
                  "valueFrom": {
                    "configMapKeyRef": {
                      "name": "apostille-signer-config",
                      "key": "db.url"
                    }
                  }
                },
                {
                  "name": "MIGRATIONS_PATH",
                  "valueFrom": {
                    "configMapKeyRef": {
                      "name": "apostille-signer-config",
                      "key": "migrations.path"
                    }
                  }
                }
              ]
            }
          ]'
    spec:
      volumes:
        - name: apostille-config
          configMap:
            name: apostille-config
            items:
              - key: config.prod.json
                path: config.json
            defaultMode: 420
        - name: apostille-signer-config
          configMap:
            name: apostille-signer-config
            items:
              - key: signer-config.json
                path: config.json
            defaultMode: 420
        - name: apostille-server-secret
          secret:
            secretName: apostille-server-secret
            items:
              - key: tls_ca
                path: ca.crt
              - key: tls_client_cert
                path: client.crt
              - key: tls_client_key
                path: client.key
        - name: apostille-signer-secret
          secret:
            secretName: apostille-signer-secret
            items:
              - key: client_ca_file
                path: ca.crt
              - key: tls_cert_file
                path: cert.crt
              - key: tls_key_file
                path: cert.key
      containers:
        - resources: {}
          name: apostille-server
          command:
            - apostille
          args:
            - -config=/etc/config/config.json
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: apostille-config
                  key: db.url
            - name: ROOT_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: apostille-config
                  key: root.db.url
          ports:
            - name: web
              containerPort: 4443
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: apostille-config
              mountPath: /etc/config
            - name: apostille-server-secret
              mountPath: /etc/secret
          image: "{{.Values.apostille_image}}"
        - resources: {}
          name: apostille-signer
          command:
            - notary-signer
          args:
            - -config=/etc/config/config.json
          env:
            - name: NOTARY_SIGNER_TIMESTAMP_1
              valueFrom:
                configMapKeyRef:
                  name: apostille-signer-config
                  key: notary.signer.timestamp.1.password
            - name: GOPATH
              value: /go/src
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: apostille-signer-config
                  key: db.url
          ports:
            - name: grpc
              containerPort: 7899
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: apostille-signer-config
              mountPath: /etc/config
            - name: apostille-signer-secret
              mountPath: /etc/secret
          image: "{{.Values.signer_image}}"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: quay-apostille-pull-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 4
  minReadySeconds: 60
